Exception on /add_to_queue/ [GET]
Traceback (most recent call last):
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matt/queue_system/app.py", line 27, in add_job_to_queue
    app.logger.info()
TypeError: info() missing 1 required positional argument: 'msg'
Exception on /add_to_queue/ [GET]
Traceback (most recent call last):
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matt/queue_system/app.py", line 29, in add_job_to_queue
    content['added_to_queue'] = datetime.now()
TypeError: 'bytes' object does not support item assignment
Exception on /add_to_queue/ [GET]
Traceback (most recent call last):
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matt/.virtualenvs/redis-venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matt/queue_system/app.py", line 29, in add_job_to_queue
    content['added_to_queue'] = datetime.now()
TypeError: 'bytes' object does not support item assignment
